// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NyscIdentify.Common.Infrastructure.Data;

namespace NyscIdentify.Common.Infrastructure.Migrations
{
    [DbContext(typeof(Context))]
    [Migration("20190502222311_AddedPhoneNumber")]
    partial class AddedPhoneNumber
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.4-servicing-10062");

            modelBuilder.Entity("NyscIdentify.Common.Infrastructure.Models.Entities.User", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("AccessToken");

                    b.Property<DateTime>("DateOfBirth");

                    b.Property<string>("Department");

                    b.Property<int>("FileNo");

                    b.Property<string>("Gender");

                    b.Property<string>("LastName");

                    b.Property<string>("OtherNames");

                    b.Property<string>("Password");

                    b.Property<string>("PhoneNumber");

                    b.Property<string>("Qualification");

                    b.Property<string>("Rank");

                    b.Property<string>("Role")
                        .IsRequired();

                    b.Property<string>("StateOfOrigin");

                    b.Property<string>("Username");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });
#pragma warning restore 612, 618
        }
    }
}
